### ISSUE TITLE
zzz_hourly_vmdb_continuous_maint No such file or directory

### ISSUE THREAD

**Issue by ProxyManagedServices** [redhat-cfme-support/DB_maint_scripts#1]
When running the zzz_hourly script for the cf 4.1 version there is an error.
./zzz_hourly_vmdb_continuous_maint: line 3: /var/www/miq/vmdb/continuous_maint/hourly_reindex_miq_servers_table: No such file or directory
./zzz_hourly_vmdb_continuous_maint: line 5: /var/www/miq/vmdb/continuous_maint/metrics_tables_continuous_pg_maint_cmd: No such file or directory

The hourly_reindex_miq_servers_table should be the hourly_reindex_metrics_tables.
The metrics_tables_continuous_pg_maint_cmd should be the metrics_tables_continuous_pg_maint

**Comment by carnott-redhat** [comment]
Thanks for the heads up; this issue should now be fixed.

**Comment by ProxyManagedServices** [comment]
There is still 1 problem with the hourly.
./zzz_hourly_vmdb_continuous_maint: line 3: /var/www/miq/vmdb/continuous_maint/hourly_reindex_miq_servers_table: No such file or directory

There is no hourly_reindex_miq_servers_table script.
There is a hourly_reindex_metrics_table script which is not called in de zzz_hourly.
