### ISSUE TITLE
hourly_reindex_miq_queue_table output 

### ISSUE THREAD

**Issue by ProxyManagedServices** [redhat-cfme-support/DB_maint_scripts#2]
Hi,

The hourly_reindex_miq_queue_table script is echoing the psql version to stdout instead of to the logfile.
When running from the zzz_hourly_vmdb_continuous_maint cron job, it will create an email everytime this script is called from cron. Thus getting everyday 24 emails with the postgres version.

I changed it to log the psql version also to the logfile instead of stdout.
echo "The version is " $(psql --version) >> /var/www/miq/vmdb/log/hourly_continuous_pg_maint_stdout.log 2>&1

**Comment by jdeubel** [comment]
This case has been updated and modified to output the details of the psql version to the hourly_continuous_pg_maint_stdout.log file. I am going to close this case.
