### ISSUE TITLE
zzz_hourly_vmdb_continuous_maint hourly_reindex_miq_servers_table not found.

### ISSUE THREAD

**Issue by ProxyManagedServices** [redhat-cfme-support/DB_maint_scripts#3]
There is still 1 problem with the hourly for the 4.1 version
./zzz_hourly_vmdb_continuous_maint: line 3: /var/www/miq/vmdb/continuous_maint/hourly_reindex_miq_servers_table: No such file or directory

There is no hourly_reindex_miq_servers_table script.
There is a hourly_reindex_metrics_table script which is not called in de zzz_hourly.

**Comment by ewannema** [comment]
Should the file in master be merged into the 4.1 branch?

**Comment by ProxyManagedServices** [comment]
That should be the solution for this.

**Comment by jdeubel** [comment]
Sorry for the delay as it seems that this email notifications was not being sent to my email. Has this been fixed or do we still need to move the file?  @ProxyManagedServices

**Comment by nmaludy** [comment]
Any update on this? @jdeubel @ProxyManagedServices

**Comment by jdeubel** [comment]
@nmaludy This file has been removed since it is not needed. Also, if you are running the later version of MIQ/CFME we have this baked into the appliance_console. That file was a redirect to point to the folder of where the scripts reside.
